//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public short Sale_Num { get; set; }
        public short SI_Qty_Sold { get; set; }
        public short SKU { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
